title: Who the hell am I?
author: tcvan1959
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am supposed to write an awesome description for my site here.

# social links
twitter_username: none
github_username:  tcvan1959

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
